import { Link, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import axios from 'axios';
const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api';
const C=createContext();
const useStore=()=>useContext(C);
const P=({children})=>{const [user,setUser]=useState(JSON.parse(localStorage.getItem('u')||'null'));const [token,setToken]=useState(localStorage.getItem('t')||'');const [cart,setCart]=useState(JSON.parse(localStorage.getItem('c')||'[]')); useEffect(()=>localStorage.setItem('u',JSON.stringify(user)),[user]);useEffect(()=>localStorage.setItem('t',token),[token]);useEffect(()=>localStorage.setItem('c',JSON.stringify(cart)),[cart]); return <C.Provider value={{user,setUser,token,setToken,cart,setCart}}>{children}</C.Provider>};
const L=()=> <header className='p-4 border-b border-gold flex justify-between'><Link to='/' className='text-gold text-2xl'>Luxe Parfum</Link><nav className='space-x-4'><Link to='/products'>Shop</Link><Link to='/contact'>Contact</Link><Link to='/cart'>Cart</Link><Link to='/profile'>Profile</Link><Link to='/admin'>Admin</Link></nav></header>;
const H=()=> <div className='p-10 text-center'><h1 className='text-5xl text-gold mb-4'>Luxury Fragrance, Redefined</h1><p className='text-gray-300 mb-8'>Discover handcrafted perfumes for every mood.</p><Link to='/products' className='btn'>Explore Collection</Link></div>;
const Products=()=>{const [d,s]=useState([]); useEffect(()=>{axios.get(`${API}/products`).then(r=>s(r.data))},[]); return <div className='p-6 grid md:grid-cols-3 gap-6'>{d.map(p=><Link key={p._id} to={`/products/${p._id}`} className='border border-gold p-3 hover:scale-[1.02] transition'><img src={p.image} className='h-64 w-full object-cover'/><h3 className='text-gold mt-2'>{p.name}</h3><p>${p.price}</p></Link>)}</div>};
const Detail=()=>{const{id}=useParams(); const [p,s]=useState(); const {cart,setCart}=useStore(); useEffect(()=>{axios.get(`${API}/products/${id}`).then(r=>s(r.data))},[id]); if(!p) return 'Loading...'; return <div className='p-6 max-w-4xl mx-auto'><img src={p.image} className='h-80'/><h2 className='text-3xl text-gold'>{p.name}</h2><p>{p.description}</p><button className='btn mt-3' onClick={()=>setCart([...cart,{...p,qty:1}])}>Add to cart</button></div>};
const Auth=({reg})=>{const n=useNavigate(); const {setUser,setToken}=useStore(); const [f,setF]=useState({name:'',email:'',password:''}); const submit=async e=>{e.preventDefault(); const url=reg?'register':'login'; const r=await axios.post(`${API}/auth/${url}`,f); setUser(r.data.user); setToken(r.data.token); n('/profile');}; return <form onSubmit={submit} className='p-6 max-w-md mx-auto space-y-3'><input required placeholder='Name' className='w-full p-2 text-black' onChange={e=>setF({...f,name:e.target.value})}/><input required type='email' placeholder='Email' className='w-full p-2 text-black' onChange={e=>setF({...f,email:e.target.value})}/><input required minLength={8} type='password' placeholder='Password' className='w-full p-2 text-black' onChange={e=>setF({...f,password:e.target.value})}/><button className='btn w-full'>{reg?'Register':'Login'}</button></form>};
const Profile=()=>{const {user,setUser,setToken}=useStore(); if(!user) return <Navigate to='/login'/>; return <div className='p-6'><h2 className='text-gold text-2xl'>Welcome, {user.name}</h2><button className='btn mt-3' onClick={()=>{setUser(null);setToken('')}}>Logout</button></div>};
const Cart=()=>{const {cart,setCart}=useStore(); const total=useMemo(()=>cart.reduce((a,b)=>a+b.price*b.qty,0),[cart]); const msg=encodeURIComponent(`Hello Luxe Parfum, I want to order: ${cart.map(i=>`${i.name} x${i.qty}`).join(', ')}. Total: $${total}`); return <div className='p-6'><h2 className='text-2xl text-gold'>Cart</h2>{cart.map((i,idx)=><div key={idx}>{i.name} - ${i.price}</div>)}<p>Total: ${total.toFixed(2)}</p><Link className='btn mr-3' to='/checkout'>Checkout</Link><a className='btn' href={`https://wa.me/1234567890?text=${msg}`} target='_blank'>Order via WhatsApp</a><button className='ml-3' onClick={()=>setCart([])}>Clear</button></div>};
const Checkout=()=>{const {cart,token}=useStore(); const n=useNavigate(); const [f,setF]=useState({fullName:'',phone:'',address:'',city:'',country:''}); const total=cart.reduce((a,b)=>a+b.price*b.qty,0); const place=async e=>{e.preventDefault(); await axios.post(`${API}/orders`,{items:cart,totalPrice:total,shippingAddress:f},{headers:{Authorization:`Bearer ${token}`}}); n('/profile');}; return <form onSubmit={place} className='p-6 max-w-md mx-auto space-y-2'>{Object.keys(f).map(k=><input key={k} required placeholder={k} className='w-full p-2 text-black' onChange={e=>setF({...f,[k]:e.target.value})}/>) }<button className='btn w-full'>Place order</button></form>};
const Admin=()=>{const {token,user}=useStore(); const [p,s]=useState([]); const [o,setO]=useState([]); const [f,setF]=useState({name:'',brand:'Luxe Parfum',price:0,description:'',category:'',image:'',stock:0}); const h={headers:{Authorization:`Bearer ${token}`}}; const load=()=>{axios.get(`${API}/products`).then(r=>s(r.data));axios.get(`${API}/orders`,h).then(r=>setO(r.data)).catch(()=>{})}; useEffect(load,[]); if(user?.role!=='admin') return <div className='p-6'>Admin access required.</div>; return <div className='p-6 grid md:grid-cols-2 gap-8'><div><h3 className='text-gold'>Manage Products</h3>{Object.keys(f).map(k=><input key={k} placeholder={k} className='w-full p-2 my-1 text-black' onChange={e=>setF({...f,[k]:e.target.value})}/>)}<button className='btn' onClick={async()=>{await axios.post(`${API}/products`,f,h);load();}}>Add</button>{p.map(i=><div key={i._id} className='flex justify-between'>{i.name}<button onClick={async()=>{await axios.delete(`${API}/products/${i._id}`,h);load();}}>Delete</button></div>)}</div><div><h3 className='text-gold'>Orders</h3>{o.map(x=><div key={x._id}>{x.shippingAddress?.fullName} - ${x.totalPrice}</div>)}</div></div>};
const Contact=()=> <div className='p-6'><h2 className='text-gold text-2xl'>Contact</h2><p>Email: support@luxeparfum.com</p><p>WhatsApp: +1 234 567 890</p></div>;
export default function App(){return <P><div className='min-h-screen bg-black text-white'><L/><Routes><Route path='/' element={<H/>}/><Route path='/products' element={<Products/>}/><Route path='/products/:id' element={<Detail/>}/><Route path='/register' element={<Auth reg/>}/><Route path='/login' element={<Auth/>}/><Route path='/profile' element={<Profile/>}/><Route path='/cart' element={<Cart/>}/><Route path='/checkout' element={<Checkout/>}/><Route path='/admin' element={<Admin/>}/><Route path='/contact' element={<Contact/>}/></Routes><footer className='border-t border-gold p-4 text-center'>© 2026 Luxe Parfum</footer></div></P>}
